# -*- coding: utf-8 -*-
"""Stock_data_query_example.ipynb

Automatically generated by Colab.

Original file is located at
    Collab Google
"""

import numpy as np
import pandas as pd
import psycopg2

conn = psycopg2.connect(database="", user="", password="", host="", port="")

# Your SQL query (you can also add it in a for loop for more complex interactions)
query = "SELECT fmp_symbol FROM public.stock_list LIMIT 10"

cur = conn.cursor()
cur.execute(query)
res = cur.fetchall()
print(res)
cur.close()

# Run this when you're done with your session
conn.close()
